version: '3.8'

services:
    mysqldb:
        image: mysql:8.4
        restart: unless-stopped
        env_file: .env
        environment:
            - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
            - MYSQL_DATABASE=$MYSQLDB_DATABASE
        ports:
            - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
        volumes:
            - ./docker/mysql/data:/var/lib/mysql

    app:
        depends_on:
            - mysqldb
        build:
            context: './'
            dockerfile: Dockerfile
        restart: on-failure
        env_file: .env
        ports:
            - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
        volumes:
            - '.:/var/www/app'
            - './src:/var/www/app/src'